@startuml Packet Tracer Tutorial

title Topologi Jaringan Cisco Packet Tracer

' Definisi Node dan Perangkat beserta IP Address
package "Subnet Node Connector A" {
    node "Server-PT\nNode Connector A\n192.168.2.2/30" as Server_A
    node "ISR4331\nRouter A\n192.168.2.1/30\n10.10.10.2/8" as Router_A
}

package "Subnet Node Connector B" {
    node "Server-PT\nNode Connector B\n192.168.3.2/30" as Server_B
    node "ISR4331\nRouter B\n192.168.3.1/30\n10.10.10.3/8" as Router_B
}

package "Subnet Node HSM" {
    node "Server-PT\nNode HSM\n192.168.1.2/30" as Server_HSM
    node "ISR4331\nRouter Hub\n192.168.1.1/30\n10.10.10.1/8" as Router_Hub
}

node "2960-24TT\nSwitch Hub Connector Jump" as Switch_Hub_Jump

package "Subnet Jump & NOC Area" {
    node "ISR4331\nRouter Jump\n192.168.4.1/24\n10.10.10.4/8" as Router_Jump
    node "2960-24TT\nSwitch Jump" as Switch_Jump
    node "Server-PT\nJump Server\n192.168.4.2/24" as Jump_Server
    node "Laptop-PT\nNOC_1\n192.168.4.3/24" as NOC_1
    node "Laptop-PT\nNOC_2\n192.168.4.4/24" as NOC_2
    node "Laptop-PT\nNOC_3\n192.168.4.5/24" as NOC_3
}

' Relasi dan Koneksi Jaringan
Server_A -- Router_A
Server_B -- Router_B
Server_HSM -- Router_Hub

Router_A -- Switch_Hub_Jump
Router_B -- Switch_Hub_Jump
Router_Hub -- Switch_Hub_Jump
Router_Jump -- Switch_Hub_Jump

Router_Jump -- Switch_Jump
Switch_Jump -- Jump_Server
Switch_Jump -- NOC_1
Switch_Jump -- NOC_2
Switch_Jump -- NOC_3

@enduml
